name: Run Tests

on:
  push:
    branches:
      - '*'  # Run on any branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: '*'
          channels: conda-forge
          activate-environment: ispy_py311
          environment-file: environment.yml
          conda-remove-defaults: "true"
          auto-activate-base: "false"

      - name: Install package
        run: |
          pip install .

      - name: Run tests
        run: |
          pytest
