name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main  # Adjust if your default branch is different
  
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Needed to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Mamba (Conda)
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: '*'
          channels: conda-forge
          activate-environment: ispy_py311
          auto-activate-base: false

      - name: Install dependencies with Mamba
        run: |
          mamba create --file environment.yml
          echo "conda activate ispy_py311" >> $GITHUB_ENV

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
