name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main  # Adjust if your default branch is different
  
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Needed to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Mamba (Conda)
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: '*'
          channels: conda-forge,nodefaults
          activate-environment: ispy_py311
          environment-file: environment.yml
          conda-remove-defaults: "true"
          auto-activate-base: "false"

      - name: Build documentation
        shell: bash -el {0}
        run: |
          pip install .
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
